import fs from "node:fs";
import ts from "typescript";
const protocol = fs.readFileSync("src/lib/metricProtocol.ts", "utf8");
const client = fs.readFileSync("src/metrics.ts", "utf8").replace(/^import .*?;\n/, "").replaceAll("import.meta.env.VITE_METRICS_OFF", JSON.stringify(process.env.VITE_METRICS_OFF ?? "false"));
const output = ts.transpileModule(protocol + "\n" + client, { compilerOptions: { target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.ES2020 } }).outputText;
fs.writeFileSync("public/metrics.js", "// Generated by scripts/build-metrics.mjs.\n" + output);
