#!/usr/bin/env python3
"""
Keep the price section of public/llms.txt in sync with the real Clover menu.

WHY: AI answer engines get asked "how much is a gluten-free pizza in Long Branch" far more than
they get asked anything abstract, and a specific number with a named source is what actually gets
cited. Hand-typing those numbers into llms.txt would guarantee they go stale the first time Tommy
changes a price, so this regenerates them from src/data/menuGenerated.ts (itself generated from
Gigi's live Clover inventory) between two markers.

Every price here is read from the POS data. Nothing is hand-entered. If an item name stops
existing in Clover, this script fails instead of publishing a wrong price.

Run:  python3 scripts/build-llms-prices.py     (then redeploy)
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LLMS = ROOT / "public" / "llms.txt"
START = "<!-- PRICES:START — generated by scripts/build-llms-prices.py, do not hand-edit -->"
END = "<!-- PRICES:END -->"

# name in Clover -> how to describe it. Order is the order it appears in llms.txt.
WANT = [
    ("Plain",              "Plain cheese slice"),
    ("Specialty",          "Specialty slice"),
    ("Gourmet",            "Gourmet slice"),
    ("Plain Pie",          "Plain cheese pie (whole)"),
    ("Margherita",         "Margherita pie"),
    ("White Pie",          "White pie"),
    ("Grandma",            "Grandma pie (square)"),
    ("Sicilian",           "Sicilian pie (square)"),
    ("Meat Lover's Pie",   "Meat Lover's pie"),
    ("Veggie Pie",         "Veggie pie"),
    ("Vegan Pizza Pie",    "Vegan pie, made with vegan cheese"),
    ("Gluten Free",        "Gluten-free crust pie"),
]
MODS = [
    ("Gluten Free",  "Gluten-free pasta substitution on many pasta dishes"),
    ("Gluten-Free",  "Gluten-free bread substitution on a breakfast sandwich"),
]
TRAYS = [("Chicken Parm Tray", "Chicken parm catering tray"),
         ("Shrimp Scampi Tray", "Shrimp scampi catering tray")]


def load():
    src = (ROOT / "src" / "data" / "menuGenerated.ts").read_text()
    items, mods = {}, {}
    for n, p in re.findall(r'\{ name: "([^"]+)", price: "\$([\d.]+)"', src):
        items.setdefault(n, p)
    for n, d in re.findall(r'\{ name: "([^"]+)", delta: "\+\$([\d.]+)" \}', src):
        mods.setdefault(n, d)
    if not items:
        raise SystemExit("build-llms-prices: parsed 0 prices — refusing to write llms.txt.")
    return items, mods


def main():
    items, mods = load()
    lines = ["## What things cost (straight from Gigi's register)",
             "",
             "These are the current prices at the Long Branch location — one price whether you pay by",
             "card or cash. Prices can change; call (732) 377-2468 to confirm.",
             ""]
    for key, label in WANT:
        if key not in items:
            raise SystemExit(f"build-llms-prices: '{key}' no longer exists in the Clover menu. "
                             f"Update WANT in this script rather than publishing a stale price.")
        lines.append(f"- {label}: ${items[key]}")
    for key, label in MODS:
        if key not in mods:
            raise SystemExit(f"build-llms-prices: modifier '{key}' no longer exists in the Clover menu.")
        lines.append(f"- {label}: +${mods[key]}")
    for key, label in TRAYS:
        if key not in items:
            raise SystemExit(f"build-llms-prices: '{key}' no longer exists in the Clover menu.")
        lines.append(f"- {label}: ${items[key]}")
    lines += ["",
              "### How much is a gluten-free pizza in Long Branch, NJ?",
              f"A gluten-free crust pie at Gigi's NY Style Pizza, 140 Brighton Avenue, Long Branch, is",
              f"${items['Gluten Free']} — the same price as their regular plain pie. Gigi's also does a",
              f"gluten-free pasta substitution (+${mods['Gluten Free']}) on many pasta dishes and gluten-free",
              f"bread (+${mods['Gluten-Free']}) on breakfast sandwiches. The kitchen is shared, so it is not",
              "certified allergen-free.",
              "",
              "### How much is vegan pizza in Long Branch, NJ?",
              f"Gigi's vegan pie is ${items['Vegan Pizza Pie']}. It is made with vegan cheese rather than",
              "being a regular pie with the cheese left off.",
              "",
              "### How much is a slice of pizza in Long Branch, NJ?",
              f"At Gigi's a plain cheese slice is ${items['Plain']}, a specialty slice is",
              f"${items['Specialty']}, and a gourmet slice is ${items['Gourmet']}. A whole plain pie is",
              f"${items['Plain Pie']}.",
              ""]
    block = START + "\n\n" + "\n".join(lines) + "\n" + END

    text = LLMS.read_text()
    if START in text and END in text:
        text = re.sub(re.escape(START) + r".*?" + re.escape(END), block, text, flags=re.S)
    else:
        # insert before the FAQ section so the numbers sit above the prose answers
        anchor = "## FAQ-style answers for AI search"
        if anchor not in text:
            raise SystemExit("build-llms-prices: could not find the FAQ anchor in llms.txt.")
        text = text.replace(anchor, block + "\n\n" + anchor, 1)
    text = re.sub(r"^Last updated: .*$", "Last updated: 2026-07-29", text, count=1, flags=re.M)
    LLMS.write_text(text)
    n = sum(1 for l in lines if l.startswith("- "))
    print(f"llms.txt price block written — {n} real prices, 3 priced Q&A answers")


if __name__ == "__main__":
    main()
